# Generated by Django 2.2.1 on 2019-10-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('type', models.CharField(choices=[(None, 'Выберите тип устройства'), ('s', 'Сирена'), ('m', 'Громкоговоритель')], default='None', max_length=1, verbose_name='Тип')),
                ('latitude', models.DecimalField(decimal_places=6, default='0.0', max_digits=10, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, default='0.0', max_digits=10, verbose_name='Долгота')),
                ('radius', models.PositiveIntegerField(default='0.0', verbose_name='Радиус')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
                'ordering': ['radius'],
                'unique_together': {('name', 'type', 'address')},
            },
        ),
    ]
